name: Python CI/CD

# Trigger on push or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - uses: actions/checkout@v3

    # 2️⃣ Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # 4️⃣ Run tests
    - name: Run tests
      run: python -m pytest

    # 5️⃣ Simulated deploy
    - name: Simulated deploy
      run: |
        mkdir -p deployed
        cp hello.py deployed/
        echo "Deployment complete"
